version: '3.8'

services:
  web:
    build: .
    container_name: family_expenses_web
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - AUTH_TRUST_HOST=true
    depends_on:
      - db
    ports:
      - "3006:3006"   # expone la app en el host (y LAN)
    volumes:
      - sqlite_data:/app/prisma   # persiste dev.db de Prisma dentro de Docker

  db:
    image: postgres:15-alpine
    container_name: family_expenses_db
    environment:
      POSTGRES_USER: web_accesoit
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: web_accesoit
    ports:
      - "5432:5432"   # para uso futuro si migras a Postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  sqlite_data:
  postgres_data:
